###
GET http://localhost:8080/
Accept: application/json

###
GET http://localhost:8080/profile
Accept: application/json



###
GET http://localhost:8080/tasks
Accept: application/json

###
GET http://localhost:8080/tasks/1
Accept: application/json



###
POST http://localhost:8080/tasks
Content-Type: application/json

{
    "title": "Tarea N",
    "decription": "Descripcion",
    "taskStatus": "COMPLETED"
    "status": 1
}









###
GET http://localhost:8080/
Accept: application/json

###
GET http://localhost:8080/profile
Accept: application/json



###
GET http://localhost:8080/languages
Accept: application/json

###
DELETE http://localhost:8080/languages/11
Accept: application/json

###
POST http://localhost:8080/languages
Content-Type: application/json

{
    "name": "SomeLanguaje",
    "last_update": "2006-02-15 05:02:19"
}


